name: brew test-bot

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-bot:
    strategy:
      matrix:
        # https://docs.github.com/en/actions/reference/runners/github-hosted-runners
        os: [
          macos-14, macos-15-intel, macos-26,
          ubuntu-22.04, ubuntu-24.04, ubuntu-22.04-arm, ubuntu-24.04-arm
        ]
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      checks: read
      contents: read
      pull-requests: read
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ matrix.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ matrix.os }}-rubygems-

      - run: brew test-bot --only-cleanup-before

      - name: Uninstall Ubuntu gnupg packages
        # Avoids test failures from conflicts system's gnupg for Homebrew gnupg@2.5
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get remove -y "gpgconf" || true;
          gpgconf 2>/dev/null && {
            dpkg-query -l "gpg*" "gnupg*"
            echo "Error: System's pre-installed gpg still exists" >&2
            exit 1
          } || true

      - name: Fix Ubuntu file privs
        # Fixes permission errors on ubuntu-*-arm
        if: startsWith(matrix.os, 'ubuntu-') && endsWith(matrix.os, '04-arm')
        run: |
          sudo chown -R runner:runner "$(brew --repository)"
          sudo chmod -R o-w "$(brew --repository)"

      - run: brew test-bot --only-setup

      - run: brew test-bot            --only-tap-syntax
      - run: brew test-bot --verbose  --only-formulae
        if: github.event_name == 'pull_request'

      - name: Build macOS x86_64 bottle
        # Bottle otherwise doesn't build because of "unbottled dependencies" error above
        if: startsWith(matrix.os, 'macos-15-intel')
        run: |
          brew install --verbose --build-bottle anthumchris/tap/gnupg@2.5
          brew bottle  --verbose                anthumchris/tap/gnupg@2.5

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: bottles_${{ matrix.os }}
          path: '*.bottle.*'
